name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests (macOS)
    runs-on: macos-14
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Show Swift Version
        run: swift --version

      - name: Run Swift Tests
        run: swift test -v
